export PROJECT = hospital-management-system
IMPORT_PATH := github.com/Abihaa/${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm \
		-v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
		${DEV_IMAGE}
